# dist: trusty # KVM Setup
# osx build as per https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-289140791

language: python
notifications:
  email: false

env:
  global:
    - CI=true

cache: pip
    #directories:
    #di- $HOME/.cache  # cython cache
    #di- $HOME/.ccache  # compiler cache

matrix:
  include:
    - os: linux
      dist: trusty
      python: "3.5"
    - os: linux
      dist: trusty
      python: "2.7"
    - os: osx
      sudo: required
      language: generic
      before_install:
      #  Manually install python on osx
      - brew update
      - brew install python3
      - virtualenv env -p python3
      - source env/bin/activate

install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install .

script:
  - flake8 . --ignore=F403,E501,E123,E128,F401,F405,E402,F821,F841,E721,E265,F811 --exclude=docs,build
  - cd examples/2sectors && python start.py
  - cd -
  - python unittest/start.py
    #- make $TEST_SUITE
