version: "{build}"
#image: Visual Studio 2017
# see https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
os: Windows Server 2012 R2
environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: 3.5
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: 3.4

build: none
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:\\Python*"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install -r requirements-dev.txt"
  - "pip install ."

test_script:
  - ps: "cd unittest"
  - "python start.py"

